### ISSUE TITLE
ART has been removed from React Native。

### ISSUE THREAD

**Issue by wangmerry** [laughing001/react-native-tcharts#3]
![image](https://user-images.githubusercontent.com/11384044/90636424-280d0800-e25d-11ea-87ab-8020ae3c2dca.png)

**Comment by laughing001** [comment]
In that upgrade ReactNative is upgraded 0.59.8 -> 0.61.4, which deprecates the ART library from RN.
具体实现可以按照这个：
https://github.com/react-native-community/art
